config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'pages#contact', as: :connection
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
  def home
    @last_year = Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>La cuillère | Test rails in Live</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 text-center">
            <h3>Contact</h3>
            <p>Le Loren Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Loren Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux
                de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié. Il a été popularisé dans les années 1960 grâce à
                la vente de feuilles.</p>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center ">
      <h1>Nous sommes le <%= @last_year %></h1>

    <% arr = %w(Alex Sam José Michel Baptiste) %>
    <ul class='list-inline'>
    <% arr.each do |person| %>
      <li><%= person %></li><br>
      <li><%= link_to "contact", connection_path %></li><br>
      <% end %>
    </ul>
    </div>
    <div>

    </div>
  </div>
</div>